#!/bin/bash

if [ "x$1" == "x" ]
then
  echo -e "Usage $0 certificate.common.name\n"
  exit
fi

URL=$1
FILE=`echo $URL | sed "s/\./_/g" | sed "s/\*/star/g"`
SUBJ="/C=AU/ST=Western Australia/L=Perth/O=Local/CN=$URL"

openssl req -new -newkey rsa:2048 -nodes \
-out $FILE.csr \
-keyout $FILE.key \
-subj "$SUBJ"

# Convert PKCS#8 key created above to PKCS#1 private key
openssl rsa -in $FILE.key -out $FILE.key

